"""Make username lower case

Peek Plugin Database Migration Script

Revision ID: b09fe7b3b31b
Revises: 73d65f042834
Create Date: 2022-01-14 13:11:12.040873

"""

# revision identifiers, used by Alembic.
revision = "b09fe7b3b31b"
down_revision = "73d65f042834"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE "core_user"."InternalUser" SET "userName" = LOWER("userName");
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
